# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
